insert into money_bag(name, budget_type, bank, banking_account_class, amount)  VALUES ('Course', 'EXPENSES', 'First Bank', 'SAVINGS',  8000.0);
insert into money_bag(name, budget_type, bank, banking_account_class, amount)  VALUES ('Parentz', 'EXPENSES', 'First Bank', 'SAVINGS',  10000.0);
insert into money_bag(name, budget_type, bank, banking_account_class, amount)  VALUES ('Sunday', 'EXPENSES', 'First Bank', 'SAVINGS',  10000.0);
insert into money_bag(name, budget_type, bank, banking_account_class, amount)  VALUES ('Tithe', 'EXPENSES', 'First Bank', 'SAVINGS',  19500.0);
insert into money_bag(name, budget_type, bank, banking_account_class, amount)  VALUES ('House Rent', 'SPEND_LATER', 'Access Bank', 'CURRENT',  21000.0);
insert into money_bag(name, budget_type, bank, banking_account_class, amount)  VALUES ('Food Stuff', 'EXPENSES', 'Access Bank', 'CURRENT',  40000.0);
insert into money_bag(name, budget_type, bank, banking_account_class, amount)  VALUES ('Transport', 'SPEND_LATER', 'First Bank', 'SAVINGS',  15000.0);
insert into money_bag(name, budget_type, bank, banking_account_class, amount)  VALUES ('Data', 'EXPENSES', 'Access Bank', 'SAVINGS',  5000.0);
insert into money_bag(name, budget_type, bank, banking_account_class, amount)  VALUES ('Fuel', 'MISCELLANEOUS', 'Access Bank', 'SAVINGS',  5000.0);
insert into money_bag(name, budget_type, bank, banking_account_class, amount)  VALUES ('Water', 'EXPENSES', 'First Bank', 'SAVINGS',  2000.0);
insert into money_bag(name, budget_type, bank, banking_account_class, amount)  VALUES ('Blessing', 'EXPENSES', 'First Bank', 'SAVINGS',  2000.0);
